# Base image.
FROM node:22.3.0-alpine

# Set environment variables.
ENV LANG=C.UTF-8

# Set arguments.
ARG NEXTJS_PORT

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY /src/package.json .

# Install packages.
RUN npm install

# Copy the code.
COPY /src .

# Build the 
RUN cmd build

# Document exposed port.
EXPOSE ${NEXTJS_PORT}

# Start app.
CMD ["npm", "start"]